ProjectAccess/ProjectAccess/Controllers/ProjectController.cs
namespace ProjectAccess.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using ProjectAccess.Areas.Identity.Data;
    using ProjectAccess.Models;

    public class ProjectController : Controller
    {
        private readonly AppDbContext dbContext;

        private readonly UserManager<AppUser> userManager;


        public ProjectController(AppDbContext context, UserManager<AppUser> userManager)
        {
            this.dbContext = context;
            this.userManager = userManager;
        }

        [HttpGet("Board/{id?}")]
        public async Task<IActionResult> Board(long? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction("Index");
            }

            try
            {
                var project = await dbContext.Projects.FindAsync(id);
                var tasks = project.Tasks;
                ViewBag.CurrentProjectName = project.ProjectName;
                ViewBag.ProjectId = project.Id;

                return View(tasks);
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Index()
        {
            var projects = new List<Project>();
            if (User.Identity.IsAuthenticated && User.IsInRole(RoleNames.Admin))
            {
                projects = await dbContext.Projects.ToListAsync();
            }
            else if (User.Identity.IsAuthenticated)
            {
                var user = await userManager.GetUserAsync(HttpContext.User);
                projects = user.UserProjects.Select(x => x.Project).ToList();
            }

            return View(projects);
        }

        public async Task<IActionResult> Details(long? id)
        {
            if (!User.Identity.IsAuthenticated || id == null)
            {
                return NotFound();
            }

            var project = await dbContext.Projects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProjectName,Description,CreationDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.GetUserAsync(HttpContext.User);
                user.UserProjects.Add(new AppUserProjects()
                {
                    Project = project,
                    ProjectId = project.Id,
                    User = user,
                    UserId = user.Id
                });
                dbContext.Add(project);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await dbContext.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,ProjectName,Description,CreationDate,EndDate")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dbContext.Update(project);
                    await dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await dbContext.Projects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var project = await dbContext.Projects.FindAsync(id);
            dbContext.Projects.Remove(project);
            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(long id)
        {
            return dbContext.Projects.Any(e => e.Id == id);
        }
    }
}

ProjectAccess/ProjectAccess/Controllers/SettingsController.cs
namespace ProjectAccess.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using ProjectAccess.Models;
    using ProjectAccess.Areas.Identity.Data;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Authorization;

    public class SettingsController : Controller
    {
        private readonly AppDbContext dbContext;

        private readonly UserManager<AppUser> userManager;

        public SettingsController(AppDbContext dbContext, UserManager<AppUser> userManager)
        {
            this.dbContext = dbContext;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize(Roles = RoleNames.Admin)]
        public async Task<IActionResult> Index()
        {
            ViewBag.CurrentUser = HttpContext.User.Identity.Name;

            return View(await dbContext.Users.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await dbContext.Users.FindAsync(id);
            ViewBag.CurrentUser = user.Id;

            var userProjects = user.UserProjects.Select(x => x.Project).ToList();
            var allProjects = await dbContext.Projects.Select(x => new ProjectRights(x, false)).ToListAsync();

            foreach (var project in userProjects)
            {
                allProjects.Where(x => x.Project.Equals(project)).First().HasRights = true;
            }

            return View(allProjects);
        }

        [HttpPut("roles")]
        [Authorize(Roles = RoleNames.Admin)]
        public async Task<IActionResult> UpdateAdminRole(long userId, bool adminRole)
        {
            var user = await dbContext.Users.FindAsync(userId);

            if (user == null)
            {
                return BadRequest();
            }

            if (adminRole)
            {
                await userManager.RemoveFromRoleAsync(user, RoleNames.User);
                await userManager.AddToRoleAsync(user, RoleNames.Admin);
            }
            else
            {
                await userManager.RemoveFromRoleAsync(user, RoleNames.Admin);
                await userManager.AddToRoleAsync(user, RoleNames.User);
            }

            dbContext.Entry(user).State = EntityState.Modified;

            await dbContext.SaveChangesAsync();

            return Ok();
        }


        [HttpDelete("user")]
        [Authorize(Roles = RoleNames.Admin)]
        public async Task<IActionResult> UpdateUserRole(long userId)
        {
            var user = await dbContext.Users.FindAsync(userId);

            if (user == null)
            {
                return BadRequest();
            }

            dbContext.Users.Remove(user);
            await dbContext.SaveChangesAsync();

            return Ok();
        }

        [HttpPut("project")]
        public async Task<IActionResult> UpdateProjectRights(long userId, long projectId, bool giveRights)
        {
            var user = await dbContext.Users.FindAsync(userId);
            var project = await dbContext.Projects.FindAsync(projectId);

            if (user == null || project == null)
            {
                return BadRequest();
            }

            if (giveRights)
            {
                user.UserProjects.Add(new AppUserProjects
                {
                    Project = project,
                    ProjectId = project.Id,
                    User = user,
                    UserId = user.Id
                });
            }
            else
            {
                var rights = user.UserProjects.Where(x => x.UserId.Equals(userId) && x.ProjectId.Equals(projectId)).Single();
                user.UserProjects.Remove(rights);
            }

            await dbContext.SaveChangesAsync();

            return Ok();
        }
    }
}

ProjectAccess/ProjectAccess/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Board.css" />
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight:500;font-size:25px">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1" style="height:37px;">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                        @if (User.IsInRole(RoleNames.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>